name: Semantic Release

on:
  push:
    branches:
      - main

concurrency:
  group: release
  cancel-in-progress: false

permissions:
  id-token: write
  contents: write
  packages: write

jobs:
  release:
    name: Semantic Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # grab full commit history instead of just the last one

      - name: Run python-semantic-release
        id: release
        uses: python-semantic-release/python-semantic-release@v10
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          git_committer_name: "github-actions"
          git_committer_email: "actions@users.noreply.github.com"

      # From here onward, we only do stuff if PSR decided that a release is necessary

      - name: Install uv # to build wheel and publish
        if: steps.release.outputs.released == 'true'
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true

      - name: Build and publish in PyPi
        if: steps.release.outputs.released == 'true'
        run: |
          rm -rf dist
          uv build --package promptuna
          uv build --package promptuna-cli
          uv build --package promptuna-server
          uv publish dist/*
        env:
          UV_PUBLISH_TOKEN: ${{ secrets.PYPI_TOKEN }}

      - name: Publish in GitHub
        uses: python-semantic-release/publish-action@v10
        if: steps.release.outputs.released == 'true'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.release.outputs.tag }}

      - name: Log in to GitHub Container Registry
        if: steps.release.outputs.released == 'true'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push container image
        if: steps.release.outputs.released == 'true'
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ steps.release.outputs.version }}
            ghcr.io/${{ github.repository }}:latest
